name: flutter_ecommerce_user
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  firebase_core: 3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  google_fonts: ^6.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.1
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  cloud_firestore: ^5.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banks/
    - assets/icons/
    - assets/icons/alert/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
